class L4Comparator:

    def compare(self, sop_sections, l4_sections):

        result = {}

        result["activity_match"] = ...
        result["missing_activities"] = ...
        result["extra_activities"] = ...
        result["role_match"] = ...
        result["application_match"] = ...
        result["control_match"] = ...
        result["recommendations"] = ...

        return result